### ISSUE TITLE
Ability not to await of remoteProvider upsert 

### ISSUE THREAD

**Issue by pkozlovskiy** [GetDutchie/brick#133]
According to the concept offline first i want immediately after sqliteProvider upsert get actual associations.
For example I show Customers with its pizzas, and then according with my UX change some pizza name and immediately(after sqliteProvider.upsert) show Customers with new pizzas.(I assume that pizzas has one to many relationships)

**Comment by tshedor** [comment]
@pkozlovskiy I'm a little bit torn on this functionality. On one hand I agree, the response should be immediate after reaching SQLite. On the other, I want to ensure that my single source of truth is updated as soon as it can be. Let me think on this a little longer and get back to you.

**Comment by KayoticSully** [comment]
I can create a new issue if this should be handled separately but I have a related question.  

If I want to store some local metadata only for the local app (a few app states that I want to persist between app launches). Is there a way to have a model that only exists locally?  Or will brick always try to persist data?  

Ive been experimenting with only fetching the model with the `OfflineFirstGetPolicy.localOnly` and upserting with `OfflineFirstUpsertPolicy.optimisticLocal` but is there a better way to just tell brick "This is a local sqlite only table/model"?

**Comment by tshedor** [comment]
@pkozlovskiy I'm going to close this since `OfflineFirstUpsertPolicy.requireRemote` is now available

**Comment by tshedor** [comment]
@KayoticSully That's an interesting question. My gut is, if the data is not complex, to use a . I'd recommend using an [OfflineFirstSerdes](https://getdutchie.github.io/brick/#/offline_first/models?id=offlinefirstserdes) model so that the data is stored in a column. If associations are necessary, however, there may be a more complex solution. 

I think this is a tangential issue that would merit its own number. Could you please open it as a separate issue?
