### ISSUE TITLE
Discussion: cache busting

### ISSUE THREAD

**Issue by dircm** [GetDutchie/brick#321]
Hello, I am wondering if anyone has a preferred cache busting / source re-fetching methodology.

Scenario:

A `OfflineFirstWithRestRepository` fetches a list of tasks from API endpoint on "server1" and caches into SQL / memory.

At a point in time, a new task is added to the "server1" and our app should refresh the repository from the API.

As far as I can tell, the `OfflineFirstWithRestRepository` wont age the cache and "check" for new tasks from the API.  Maybe some sort of polling or event prompts our Flutter app to update ?

How could I implement this ?

Thanks, Tom.

**Comment by tshedor** [comment]
Hey @dircm , there are a couple ways to do this. Every API is different, so the Brick system is admittedly vague on how to handle updates, instead leaving it to the implementation.

1. Receive updates asynchronously. You could have something like a short poll for changes or for individual models. Short polls, in my experience, have led to memory leaks in Flutter, so be careful with this. For this, you should use the protected repository method `storeRemoteResults` to apply results to SQLite and MemoryProvider.
2. Use the `alwaysHydrate: true` argument. This will ensure that your app will consistently refresh data whenever it makes a local request. This will be more expensive on your server as you're making more requests, and the data will only show on subsequent repository requests. You could most easily do this by subclassing the repository's methods and adding `alwaysHydrate:true` as the default (i.e. `super.get<_Model>(alwaysHydrate: true, ....)`)
3. Add a property that tracks requerying your API. This could be added to a super class that all models inherit from. You could then set up a short poll system that sorts by this timestamp, grabbing the latest one for each of your models, and querying the API if it exceeds your tolerated window. You may not need this for every model.

For 1 and 3, I'd recommend writing a mixin so that your core repository logic remains clean and maintainable. 

I am adding a feature in Brick 3 called `subscribe` that mimics the [GraphQL provider's functionality](https://github.com/GetDutchie/brick/blob/main/packages/brick_offline_first_with_graphql/lib/src/offline_first_with_graphql_repository.dart#L163-L189) to notify Dart listeners when new data hits the SQLite instance. This would permit 2. to be viable as it would update the displayed data as soon as the remote resolved with its data. 

Does that answer your question?

**Comment by tshedor** [comment]
@dircm there is no built-in `refresh` method because REST APIs tend to be very different, but this architecture could be built by an implementation. 

REST will only re-read the API upon an upsert **if** `autoHydrate` is `true` when you instantiate your repository.

**Comment by dircm** [comment]
Thanks Tim.
