### ISSUE TITLE
Example doesn't work and doesn't show server errors

### ISSUE THREAD

**Issue by hortigado** [GetDutchie/brick#345]
Hi, I'm trying brick with api rest but it doesn't show me the data. I tried with the local server of the example and nothing, so I tried with other remote ones and the same thing, I don't get the data. How could I see the server error why the data is not displayed? because in the console it does not throw me an error. It only returns the empty list

**Comment by hortigado** [comment]
I already managed to get the data, I forgot to put the header, but I still want to be able to print the server error, how can I do it?

**Comment by hortigado** [comment]
Also when using the toppings attribute from the example which is an enum, it throws the following error
`_TypeError (type '(String) => Topping' is not a subtype of type '(dynamic) => dynamic' of 'f')`

**Comment by tshedor** [comment]
@hortigado please `git checkout main; git pull` and try the example again. Thank you for opening the issue. 

If this doesn't solve your problem, please comment on this issue and I'll reopen it.

**Comment by hortigado** [comment]
@tshedor  Hi thanks for the package, its great. Correct was it resolved attribute  topping of the example. 
I still have the question how we can get the responses from the server. Since it would be useful for me to be able to resolve errors on the part of the server.

**Comment by tshedor** [comment]
@hortigado the server [responds](https://github.com/GetDutchie/brick/blob/main/example_rest/server.dart#L18) with static [JSON files](https://github.com/GetDutchie/brick/tree/main/example_rest/_api). If you're trying to debug what the server provides, I'd recommend using a CLI utility (for example, `curl http://localhost:8080/pizzas`) or inserting a `print(resp)` statement [between lines 18 and 19](https://github.com/GetDutchie/brick/blob/main/example_rest/server.dart#L19) before running `dart server.dart`.

**Comment by tshedor** [comment]
@hortigado good to close this out?

**Comment by hortigado** [comment]
@tshedor Hello, tonight I try the recommendations, but what I want is to obtain the response codes from the remote server https://appwrite.io/docs/response-codes in my case these would be.

**Comment by tshedor** [comment]
@hortigado you want to obtain the response codes where? From the response of `upsert`? How would you use them? 

I would recommend subclasses [RestProvider](https://github.com/GetDutchie/brick/blob/main/packages/brick_rest/lib/src/rest_provider.dart) and passing that to your [repository](https://github.com/GetDutchie/brick/blob/main/example_rest/lib/brick/repository.dart#L13) on initialization. That way you can [capture http codes](https://github.com/GetDutchie/brick/blob/main/packages/brick_rest/lib/src/rest_provider.dart#L98) and use them for whatever you need before Brick does its thing.

**Comment by hortigado** [comment]
@tshedor  Correct, for example, it is useful for me to know why an item is not inserted in the server, whether I am missing an attribute or another similar error. Also to show errors to the user, such as when he exceeds the limit of items per time.
I'm going to try tomorrow what my friend suggests, now I'm trying to refer to the parent item from the child item and; I'm having difficulties.
For example i have:
**Parent:** Customer
**Children:** Pizza
I want to be able to get the parent from the child item. For example pizza.customer.name

**Comment by tshedor** [comment]
@hortigado If you're dependent on the server's responses, that goes against the principle of Brick's `OfflineFirst`. You could make every request with `OfflineFirstUpsertPolicy.awaitRemote` too.

I think the best thing you can do is intercept the server response by subclassing `RestProvider` or subclassing [your own HTTP Client](https://github.com/GetDutchie/brick/blob/main/packages/brick_rest/lib/gzip_http_client.dart) that logs out server responses in development.

**Comment by tshedor** [comment]
@hortigado In the future, it'd definitely be useful to open a new issue - it helps others find their questions/answers quickly and, selfishly, keeps my TODO list organized. I'll answer your question here -

Bidirectional associations are not possible because of cyclical fetching. That's some word vomit, so here's what I mean:
1. No customers or pizzas exist.
2. Customers are fetched. Because no pizzas exist, pizzas are also fetched
3. While pizzas are being fetched, customers are fetched _again_ as an association because customers have not been persisted because the original "fetch customers" task is still fetching pizzas. 

In the projects where I've used Brick, I've gotten around this in two ways:
1. Make the data flow - parent to children or children to parent - work in your state/UI. 
2. Perform a query for your rare edge cases: `await (Repository().get<Customer>(query: Query.where('customerId', pizza.customerId, limit1: true))).first`. This may require storing a second field in your model, like a `final String customerId`, but it's dependent on the data you're getting from the server.

This is noted in the docs as [unsupported types](https://github.com/GetDutchie/brick/tree/main/packages/brick_rest#unsupported-field-types) but without the additional explanation. You're right that this should be more pronounced and clear, or at least have some explanation.

**Comment by hortigado** [comment]
@tshedor Thank you very much for the answer,
I will have to do a manual query then. As I am implementing brick in a project where **Objectbox** was used as local storage manager. And since it allows bidirectional association I already have all the code with that feature, I wanted to avoid the task of modifying every part where this type of association is used. But hey I think it was my turn to do it in the end. 
As I mentioned before thank you very much for the package, it works very well, I will make a guide blog on how to implement brick in a few days. Greetings

**Comment by hortigado** [comment]
@tshedor  Thank you very much for the answer, I will have to do a manual query then. 
As I am implementing brick in a project where **Objectbox** was used as local storage manager. And since it allows bidirectional association I already have all the code with that feature, I wanted to avoid the task of modifying every part where this type of association is used. But hey I think it was my turn to do it in the end. 
As I mentioned before thank you very much for the package, it works very well, I will make a guide blog on how to implement brick in a few days. Greetings

**Comment by tshedor** [comment]
@hortigado Objectbox looks sweet. Thanks for sharing that. I've never heard of that before. A good number of Brick's constraints are built around the uncertainty and disparity of REST APIs. An end-to-end solution like this is really sweet.
