### ISSUE TITLE
Add http ^1.0.0 support

### ISSUE THREAD

**Issue by Mikhail-Ivanou** [GetDutchie/brick#361]
Now brick_offline_first_with_rest 3.0.1 depends on http ^0.13.0
Some other libraries wants http ^1.0.0 already. 

It will be great brick will use http ^1.0.0 soon too

**Comment by tshedor** [comment]
Hey @Mikhail-Ivanou thanks for using Brick. The latest version of `offline_first_with_rest` supports `http` versions `>=0.13.0 <2.0.0` [already](https://github.com/GetDutchie/brick/blob/main/packages/brick_offline_first_with_rest/pubspec.yaml#L20).

I've seen http be installed at a much lower version on vanilla Flutter projects but haven't tracked down the exact dependency that's forcing it (my money is on `test` since a lot of those dependencies are pinned to a specific version). Are you sure that Brick is the one forcing `0.13.0`?

**Comment by tshedor** [comment]
@Mikhail-Ivanou going to close this due to inactivity
