### ISSUE TITLE
Feature: Synchronized app indicator

### ISSUE THREAD

**Issue by hortigado** [GetDutchie/brick#365]
Hello, I think that a feature that could be implemented would be to be able to show the user if their information is synchronized or when was the last date that it was synchronized. Regards

**Comment by tshedor** [comment]
Hey @hortigado this is tricky because Brick doesn't synchronize all data at once. It synchronizes on demand. I'd recommend adding an `updatedAt` property to you Dart model and only assigning it on remote update:

```dart 
@Rest(fromGenerator: 'DateTime.now()', ignoreTo: true)
final DateTime updatedAt;
```

If you need to access it for all models, you can write a SQL query to pull only the relevant data out: 

```dart
AppRepository().get<MyModel>(
  query: Query(
    providerArgs: {
      'limit': 1, 
      'orderBy': 'updatedAt DESC'
    }
  )
)
```
