### ISSUE TITLE
multipart request

### ISSUE THREAD

**Issue by abhitheawesomecoder** [GetDutchie/brick#380]
support for multipart request

**Comment by tshedor** [comment]
For what? For REST?

**Comment by abhitheawesomecoder** [comment]
Yes.

If I try to send files as one of the field in post request, will it work?

Also I feel if documentation can be more easy to understand the package
could have gained more popularity.

**Comment by tshedor** [comment]
Multipart is not supported because...well to be honest I never thought a multipart would be necessary in an offline scenario. If the user is uploading a file, they already have that file on their device. That's not to say that _theoretically_ this is impossible. Brick is just a thick wrapper around the native `http` library, so you could simply change [your request headers using a `RequestTransfomer` to the right mime type](https://getdutchie.github.io/brick/#/rest/models?id=restserializablerequesttransformer) and that could work. 

Multipart is not mentioned in the documentation because it's not supported. If you have specific suggestions on where to improve the documentation, I'm open to hearing them. This package tries to accomplish a lot, and it's difficult to provide clear explanations that solve low-level problems (like this one) while also explaining high-level concepts (like when you'd want to use Brick) without being completely overwhelming.

**Comment by abhitheawesomecoder** [comment]
I tried to follow all the steps mentioned in quick start and run the example_rest on android but I am getting blank(white) screen and get request for customers is returning null. (I am running the server and on brower customers endpoint is returning customers).

**Comment by tshedor** [comment]
<img width="354" alt="image" src="https://github.com/GetDutchie/brick/assets/865897/9a3e4c45-3354-482a-ad50-28b819a949c5">

```
flutter: null
flutter: [Instance of 'Customer']
```

Can you make an `http.get('http://10.0.2.2:8080/customers')` request on your Android device? Android can be difficult with localhost. You may also need to try `0.0.0.0` or watch the `adb logcat` stream to ensure your device is connecting to your localhost service.

**Comment by abhitheawesomecoder** [comment]
Yes it worked but not with the server.dart. I ran another server with express/nodejs with same endpoint and response and it worked. 

I have one more doubt. If I make upsert and the request failed due to no internet connection. Will there be further automatic request later (when internet is available)?

**Comment by hortigado** [comment]
@abhitheawesomecoder Correct, the request replay if the code response it in `reattemptForStatusCodes`. You can edit it in your `Repository`
```
  /// If the response returned from the client is one of these error codes, the request
  /// **will not** be removed from the queue. For example, if the result of a request produces a
  /// 404 status code response (such as in a Tunnel not found exception), the request will
  /// be reattempted.
  ///
  /// Defaults to `[404, 501, 502, 503, 504]`.
  final List<int> reattemptForStatusCodes;
```

**Comment by tshedor** [comment]
@abhitheawesomecoder @hortigado is correct. There is a way to tweak what failed error codes are stored in the retry cache.  You can read more on the [cache here](https://getdutchie.github.io/brick/#/offline_first/offline_queue) and about the [offline architecture here](https://getdutchie.github.io/brick/#/offline_first/offline_first_with_rest_repository).
