### ISSUE TITLE
Remove Items From Outbound Queue

### ISSUE THREAD

**Issue by SubutaDan** [GetDutchie/brick#395]
Apologies if this is in the doc. and I have overlooked it.

I am using offline first with REST. I would like to make it possible from within my app. for the end user to remove a pending outbound operation or perhaps even flush the outbound queue if, for some reason, an operation is repeatedly rejected by the REST server. 

Is this a terrible idea?

How can the queue be accessed and items removed?

As always, thanks for the help.

-Dan

**Comment by devj3ns** [comment]
Hey Dan, I think I can help here.

There is a method called [deleteUnprocessedRequest](https://github.com/GetDutchie/brick/blob/278aa99186f53fe43670bfbe78e7fd31815a337f/packages/brick_offline_first/lib/src/offline_queue/request_sqlite_cache_manager.dart#L59) on the `RequestSqliteCacheManager` class. 

With this, you can delete a request by its ID. To delete all requests from the queue, you can do the following:

```
// Delete all unprocessed requests from the offline queue:
final requests = await repository.offlineRequestQueue.client.requestManager.unprocessedRequests();
final requestsToDelete = requests.map((request) {
  final primaryKeyColumn = dataRepository.offlineRequestQueue.client.requestManager.primaryKeyColumn;
  final requestId = request[primaryKeyColumn] as int;

  return dataRepository.offlineRequestQueue.client.requestManager.deleteUnprocessedRequest(requestId);
});
await Future.wait(requestsToDelete);
```
---

I am currently dealing with this problem as well. In the app I am building, a POST request could be rejected by the server because it contains outdated data and would override newer data in the remote db. In this case, the complete request queue is permanently stuck if the user can't intervene (due to serial processing).
To address this, I'm planning to implement a feature allowing users to discard the oldest (currently attempted) request to unblock the queue. However, this approach presents the following challenges

- How to detect if a request will never succeed to then give the user the option to delete this request? Brick currently only stores the number of attempts and the time of the last attempt. Without additional measures, it's impossible to differentiate between a request that failed due to connection issues and one rejected by the REST API. In https://github.com/GetDutchie/brick/issues/393 we are discussing a proposal of adding the API response to the offline queue. This would allow us to identify which requests were explicitly rejected by the server.

I would be happy to get your thoughts on this. I consider offline first a very interesting topic, and brick is a great foundation for this!

**Comment by SubutaDan** [comment]
Hi devj3ns,

Thanks so much for the reply.  I will try your suggestion.

ATM there is no case where I want my backend to reject a request, but I may need that functionality in the future.  Even in my current case though, it would be a mistake to delete an item if it had failed because of a connectivity issue as you mentioned.

Being able to find the reason for a failure sounds like it would be useful., but I am not well versed in this topic, so please take my opinions with a large grain of salt. :)

I think I have observed that failed items are retried automatically by Brick, but I haven't looked into this carefully.  

I have a long way to go to get to seamless offline-first, but I hope to get there eventually with Brick.

-Dan

**Comment by SubutaDan** [comment]
I am closing this issue now, and will return to the question if I am unable to use the methos that @devj3ns suggested.  -Dan

**Comment by SubutaDan** [comment]
I am closing this issue now, and will return to the question if I am unable to use the method that @devj3ns suggested.  -Dan
