### ISSUE TITLE
Supabase Example Not Working

### ISSUE THREAD

**Issue by jtkeyva** [GetDutchie/brick#446]
Cannot run app. I added print statement and it never reaches
print('Initialized Supabase and Repository');

Future<void> main() async {
  print('Initializing Supabase and Repository');
  await Repository.initializeSupabaseAndConfigure(
    supabaseUrl: supabaseUrl,
    supabaseAnonKey: supabaseAnonKey,
  );
  print('Initialized Supabase and Repository');
  await Repository().initialize();
  print('Initialized Repository');
  runApp(MyApp());
}

**Comment by tshedor** [comment]
@jtkeyva thanks for opening a new issue. 

Have you replaced the URL and anon values? Have you run this with All Exceptions enabled to see where the exception is being thrown?

**Comment by jtkeyva** [comment]
Yes I have my supabase info in there. No exceptions...just a white screen.

**Comment by tshedor** [comment]
@jtkeyva I was able to run the app, and I only changed the placeholders and added print statements:

```
Running Xcode build...
 └─Compiling, linking and signing...                      2,016ms
Xcode build done.                                           11.2s
flutter: start
flutter: ***** Supabase init completed Instance of 'Supabase'
flutter: ***** SupabaseDeepLinkingMixin startAuthObserver
flutter: **** onAuthStateChange: AuthChangeEvent.initialSession
flutter: configured
flutter: done
```

Please make sure this is a fresh install (i.e. delete the app on your device or simulator if it's already there).

**Comment by jtkeyva** [comment]
aha, yes i deleted the app and it works thanks. 

the demo doesn't do much to show "off" the offline capabilities. also i changed a name in the database and it never "inhaled" the changes even after app restart. perhaps an add customer would be cool too.

**Comment by tshedor** [comment]
@jtkeyva It's a minimal example. It should be just enough to be a starting point. PRs are welcome if you want to add more necessary functionality.

It won't ingest the remote changes unless [you use an](https://github.com/GetDutchie/brick/blob/main/packages/brick_offline_first_with_graphql/lib/src/offline_first_graphql_policy.dart) `OfflineFirstGetPolicy` that grabs from the remote (`.awaitRemote` or `.alwaysHydrate`). Otherwise, the repository defers to retrieving the offline data first.

**Comment by jtkeyva** [comment]
got it thanks for this! i was messing around with drift but this may be all that is needed. could/should it be one or the other or will they play nice?

**Comment by tshedor** [comment]
@jtkeyva I've only admired drift from afar and haven't used it in conjunction with Brick. However, it has its own build system which would likely interfere with Brick's. Brick could certainly access the database Drift has built, but since Brick maintains an internal SQLite primary key, it may take some calibration with generated migrations to connect existing Drift data. I also don't know how Drift works with Supabase. 

Otherwise, for reactive local changes that is sort of Drift's big selling feature, you can invoke `.subscribe` on the repository.

**Comment by jtkeyva** [comment]
aha thanks. oh wow so you you have managed to sneak reactivity in under the radar? i feel that's a pretty standout feature in of itself :)

i did a chatgpt and it stated that drift was more geared towards complex queries and joins whereas brick is more for simple queries. is that correct? perhaps there is no need for drift with brick?

this is a drift / offline pocketbase example
https://github.com/rodydavis/pocketbase_drift

and another drift
https://github.com/rodydavis/signals.dart/tree/main/examples/drift_example

**Comment by tshedor** [comment]
@jtkeyva Like I said, I really don't know the intricacies of Drift, so this comparison could be ill-informed. I believe Drift is geared toward writing your own SQL but managing your model logic in Dart. 

Brick is an ORM/ORM-ish library. It won't give you the most optimized version of a SQL query, but in 5 years of using Brick, I think I've only had to handroll a SQL query once (which you can do using `rawGet`, `rawInsert`, `rawExecute`, or even `rawQuery` on Brick's `SqliteProvider`). 

So, I think ChatGPT is right there in that Brick is for simple queries. And simple queries are most likely all you need, since a SQLite instance on a device should not be storing and querying over millions of rows.

**Comment by tshedor** [comment]
@jtkeyva I'm going to close this issue since the original problem has been resolved.

**Comment by jtkeyva** [comment]
thank you for the explanation!
