### ISSUE TITLE
How to use both supabase and res

### ISSUE THREAD

**Issue by sonbs21** [GetDutchie/brick#463]
When use both brick_offline_first_with_rest_build and brick_offline_first_with_supabase_build and build-runner has error
`Both brick_offline_first_with_supabase_build:brick_aggregate_builder and brick_offline_first_with_rest_build:brick_aggregate_builder may output lib/models_and_migrations.brick_aggregate.dart. Potential outputs must be unique across all builders. See https://github.com/dart-lang/build/blob/master/docs/faq.md#why-do-builders-need-unique-outputs`

Not sure if it's possible to use both?

**Comment by tshedor** [comment]
@sonbs21 It is not possible to use two different builders on the same model. However, it should be possible to use one builder on one model - so you'd have a `RestUser` model and a `SupabaseUser` model. 

However, I don't understand the use case as to why you'd want or need to use these two different domains. Perhaps you can describe your end goal?

**Comment by tshedor** [comment]
@sonbs21 Right...ok this example helps. So you have two different datasources that you're trying to put into one place.

Generally, it is possible with maybe some scripting and maybe some patience. The problem is that both of these builders are trying to write to `brick.g.dart` and `schema.g.dart`. To get around this:

1. Comment out `brick_offline_first_with_supabase_build` in your `pubspec.yaml`. 
1. Run the `dart run build_runner`. 
1. Rename `brick.g.dart` to `brick.rest.g.dart` (`cp lib/brick/brick.g.dart lib/brick/brick.rest.g.dart`). Do the same for `schema.g.dart`
1. Comment out `brick_offline_first_with_rest_build` in your `pubspec.yaml`. Uncomment `brick_offline_first_with_supabase_build`
1. Repeat the above steps without renaming `brick.g.dart` or `schema.g.dart`.

Now, since you have two distinct remote providers, your best option is to create two different repositories. You can try sharing the same SQLite database name, but this may affect how migrations are computed and run, so it'd be best to have two different SQLite databases. You could also, theoretically, have one repository with two remote providers.

**Comment by tshedor** [comment]
Hopefully you won't have to change the model too often. I agree that it's cumbersome. You could write a shell script to make it go a little easier.
