### ISSUE TITLE
Wrong conversion of double values

### ISSUE THREAD

**Issue by JCKodel** [GetDutchie/brick#471]
I'm using Hasura. In my database, there are 2 real columns.

The adapter is created as this:

```dart
return Device(
  ...
  osVersion: data['os_version'] as double,
  ...
);
```

But, somehow, `data['os_version']` containing a `3` is `int` and that line fails with an invalid cast (I could not reproduce this behaviour in DartPad, any map with an int IS castable to double, but, anyway...)

I had to write this custom serializer to make it work:

```dart
@Graphql(fromGenerator: "data['os_version'].toDouble()")
final double osVersion;
```

I would recommend to the default serializer to use `data['os_version'].toDouble()` (or `data['column'].toInt()` when it is an int).

**Comment by tshedor** [comment]
@JCKodel sorry for the delayed response, I was on vacation.

Instead of `double`, could you use `num` in your model instead? It sounds like your API or Supabase instance could return either an `int` or `double`, and the Dart equivalent for that logic is `num`. This will be serialized as a `Double` [when it gets to SQLite anyway](https://github.com/GetDutchie/brick/blob/main/packages/brick_sqlite/lib/src/db/migration.dart#L21-L22).

**Comment by JCKodel** [comment]
@tshedor No. I cannot. `int` is `int`, `double` is `double`.

**Comment by tshedor** [comment]
@JCKodel Well...`double` is `double` but you're receiving the value as an `int` from your remote provider, so it's not a `double`. Can you explain more about why you can't use `num` in Dart?

**Comment by tshedor** [comment]
Prematurely closed; will close tomorrow if there's no more discussion
