### ISSUE TITLE
"DELETE requires a WHERE clause" while trying to delete a column from Supabase

### ISSUE THREAD

**Issue by BeLikeSohan** [GetDutchie/brick#477]
When we call the Repository().delete() function we are required to pass a instance of the model we want to delete. but if the instance doesnt contains any id field it throws this error.
But if we add a id field in the model we cant upsert it anymore because now we have to pass an id from the code to the model before upserting, but id is auto generated in the supabase, we are not supposed to pass it from app.
If we make the id field nullable and dont pass it during upsert it throws an error from supabase saying the id field is null.

How should we deal with this situation. I am very sorry I couldnt provide any code snippet. I am trying to find a workaround this for 3 days straight and now I do not have the mental energy to spend on it anymore.
Thanks for understanding

**Comment by tshedor** [comment]
Hi @BeLikeSohan 

> instance doesnt contains any id field it throws this error

Can you please provide the error? I need to know if it's from Supabase or Brick

> If we make the id field nullable and dont pass it during upsert it throws an error from supabase saying the id field is null.

You can override the `upsertByType` field in `SupabaseProvider` to remove fields, although I would strongly recommend against doing this. If your database has an autoincrement `id`, it's not a truly offline first system. The primary key in the database should be a `uuid` and the autoincremented `id` should be nullable. 

I'll provide the code for overriding `upsertByType` soon

**Comment by richard457** [comment]
@tshedor from your comment the id should be uuid? what if it is int but not incremented is there a cons to that

**Comment by BeLikeSohan** [comment]
> Hi @BeLikeSohan
> 
> > instance doesnt contains any id field it throws this error
> 
> Can you please provide the error? I need to know if it's from Supabase or Brick
> 
> > If we make the id field nullable and dont pass it during upsert it throws an error from supabase saying the id field is null.
> 
> You can override the `upsertByType` field in `SupabaseProvider` to remove fields, although I would strongly recommend against doing this. If your database has an autoincrement `id`, it's not a truly offline first system. The primary key in the database should be a `uuid` and the autoincremented `id` should be nullable.
> 
> I'll provide the code for overriding `upsertByType` soon

Thanks for replying. I will provide the error message asap. 
You said that I should use primary key as uuid and a separate id field for autoincrement. I can modify my db to use uuid as primarykey. Will that solve the issue?
If I use primarykey(uuid), and id(nullable) what should I pass to these field while upserting and deleting?
Thanks again for the help.

**Comment by tshedor** [comment]
> from your comment the id should be uuid? what if it is int but not incremented is there a cons to that

The primary key should be a UUID. I would avoid having this be an int because, if your app is offline first, clients can easily create the same integers, leading to collisions when they're uploaded (unless your int is a nanosecond derived from current time, but even then there's little guarantee). However, you can create the `uuid` [on the client](https://pub.dev/packages/uuid), i.e. `MyModel({String? uuid}) : uuid = uuid ?? Uuid().v4();`. 

> You said that I should use primary key as uuid and a separate id field for autoincrement. I can modify my db to use uuid as primarykey. Will that solve the issue?

I think so, yes. Again, I need to see your error because I'm not sure if it's Brick or Supabase, but based on the information that I have, I believe the error is in Supabase because you are not yet generating the PK on the client.

> If I use primarykey(uuid), and id(nullable) what should I pass to these field while upserting and deleting?

If you can change your DB to use the uuid as the PK, you should no longer need the `id` column. When you're upserting and deleting, you pass the instance of the Brick model. So if the Brick model has a present PK (the `uuid`), it should map with the PostgREST validations from the Supabase client and Brick's synchronization of local state.

**Comment by BeLikeSohan** [comment]
Thanks, after modifying my db to use uuid as PK it fixed the issue. Now both upsert and delete is working.

Here is my codes incase someone faces this issue in the future.

model file:
`  @Sqlite(index: true, unique: true, name: "id")
  @Supabase(unique: true, name: "id")
  final String? id;

  RunningClassModel({
    String? id,
    .......
  }) : id = id ?? Uuid().v4();`


Thanks again for this plugin.
