### ISSUE TITLE
Offline only data

### ISSUE THREAD

**Issue by saniul1** [GetDutchie/brick#509]
How to keep some data offline and not let it sync to cloud (also how to reject data from cloud after some limit (lets say 10 row) even if client (brick) try to submit). thank you @tshedor

**Comment by tshedor** [comment]
> How to keep some data offline and not let it sync to cloud

@saniul1 you can access providers directly (`Repository().sqliteProvider`) or have two different repositories - one that manages offline/remote models and one that doesn't. However, I would recommend that you just use the appropriate `OfflineFirstGetPolicy` and `OfflineFirstUpsertPolicy` when making your repository requests.

> also how to reject data from cloud after some limit (lets say 10 row) even if client (brick) try to submit

This will have unexpected consequences especially if you're using associations. The client may expect data to exist where it doesn't because it's been rejected. 

If you really must do this - **and I can't emphasize enough that you should not** - you could access the `onReattempt` callback within the Supabase or REST repositories. Your server should send a unique status code like 406. In the callback, you can then delete with something like this untested, unguaranteed code:

```dart
onReattempt: (request, statusCode) {
  final unprocessedRequests = await Repository().offlineRequestQueue.requestManager.unprocessedRequests();
  if (statusCode != 406) return;
  final unprocessedRequest = unprocessedRequests.firstWhere((r) => ...); // find your request
  if (unprocessedRequest[HTTP_JOBS_ATTEMPTS_COLUMN] < 10) return;
  await Repository().offlineRequestQueue.requestManager.deleteUnprocessedRequest(unprocessedRequest[HTTP_JOBS_PRIMARY_KEY_COLUMN]);
}
```

**Comment by saniul1** [comment]
@tshedor so you are saying i mange two database file one for offline one for sync. I was considering this but hesitant about managing two databases but if i can handle it with same code base, then theres no problem. would you privide some code or best practices on how go ahead with this. thank you.

**Comment by tshedor** [comment]
> you are saying i manage two database file one for offline one for sync. I was considering this but hesitant about managing two databases but if i can handle it with same code base, then there's no problem.

This is an option, but I don't think it's your best option. Your business logic will be split and will become difficult to maintain.

> would you provide some code or best practices on how to go ahead with this. thank you.

Like I said, I would recommend that you just use the appropriate `OfflineFirstGetPolicy` and `OfflineFirstUpsertPolicy` when making your repository requests, especially if you want to sync these models later. You can [read more about policies here](https://getdutchie.github.io/brick/#/offline_first/policies).

**Comment by saniul1** [comment]
there's no `OfflineFirstUpsertPolicy.localOnly`
how to not send data to remote in the first place.

**Comment by tshedor** [comment]
If you're only using the `SqliteProvider`, you can access it directly with `Repository().sqliteProvider.upsert<Model>`. You should not use the `memoryCacheProvider` to maintain sync of your data.
